import crypto from 'node:crypto';

/**
 * AES-256-GCM Encryption-at-Rest Module
 * Spec: MASTER_PROMPT Phase 11 & docs/SAFETY_AND_PRIVACY.md
 * Encrypts stored patient documents and clinical data at rest with authenticated encryption.
 */

const ALGORITHM = 'aes-256-gcm';
const IV_LENGTH_BYTES = 12; // 96-bit IV recommended for GCM
const AUTH_TAG_LENGTH_BYTES = 16; // 128-bit authentication tag
const SALT = 'medscribe-doc-enc-salt-v1';

// Derive 32-byte key from environment or fallback dev key
function getEncryptionKey(): Buffer {
  const envKey = process.env.DOC_ENCRYPTION_KEY || 'medscribe-demo-master-key-32b!!';
  return crypto.scryptSync(envKey, SALT, 32);
}

/**
 * Encrypts any string, Buffer, or JSON-serializable object using AES-256-GCM.
 * Output format: enc:v1:<iv_hex>:<authTag_hex>:<ciphertext_hex>
 */
export function encryptPayload(data: string | Buffer | Record<string, any>): string {
  const plaintext = typeof data === 'string' 
    ? data 
    : Buffer.isBuffer(data) 
      ? data.toString('utf-8') 
      : JSON.stringify(data);

  const key = getEncryptionKey();
  const iv = crypto.randomBytes(IV_LENGTH_BYTES);
  const cipher = crypto.createCipheriv(ALGORITHM, key, iv);

  let ciphertext = cipher.update(plaintext, 'utf8', 'hex');
  ciphertext += cipher.final('hex');

  const authTag = cipher.getAuthTag();

  return `enc:v1:${iv.toString('hex')}:${authTag.toString('hex')}:${ciphertext}`;
}

/**
 * Decrypts an authenticated ciphertext string generated by encryptPayload.
 * Throws an Error if the ciphertext has been tampered with or is corrupted.
 */
export function decryptPayload<T = any>(encryptedString: string, asJson = true): T {
  if (!isEncrypted(encryptedString)) {
    throw new Error('Invalid encrypted payload format. Expected enc:v1:<iv>:<tag>:<ciphertext>');
  }

  const parts = encryptedString.split(':');
  if (parts.length !== 5) {
    throw new Error('Malformed ciphertext payload structure');
  }

  const iv = Buffer.from(parts[2], 'hex');
  const authTag = Buffer.from(parts[3], 'hex');
  const ciphertext = parts[4];

  if (iv.length !== IV_LENGTH_BYTES || authTag.length !== AUTH_TAG_LENGTH_BYTES) {
    throw new Error('Invalid IV or Auth Tag length');
  }

  const key = getEncryptionKey();
  const decipher = crypto.createDecipheriv(ALGORITHM, key, iv);
  decipher.setAuthTag(authTag);

  let decrypted = decipher.update(ciphertext, 'hex', 'utf8');
  decrypted += decipher.final('utf8');

  if (asJson) {
    try {
      return JSON.parse(decrypted) as T;
    } catch {
      return decrypted as unknown as T;
    }
  }

  return decrypted as unknown as T;
}

/**
 * Checks whether a given string is in the standard encrypted payload format.
 */
export function isEncrypted(value: unknown): boolean {
  if (typeof value !== 'string') return false;
  return value.startsWith('enc:v1:') && value.split(':').length === 5;
}
